"""Balans sahifasi — rasmdagi kabi gradient + ikkita kartochka."""
from __future__ import annotations
from typing import Optional
from PyQt6.QtCore import Qt
from PyQt6.QtGui import QColor, QFont
from PyQt6.QtWidgets import QFrame, QGraphicsDropShadowEffect, QHBoxLayout, QLabel, QSizePolicy, QVBoxLayout, QWidget
def _fmt(value: float) -> str:
    return f'{float(value or 0):,.0f}'.replace(',', ' ')
class BalancePage(QWidget):
    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        self.setObjectName('BalancePage')
        self.setStyleSheet('QWidget#BalancePage { background: #F5F6F8; }')
        root = QVBoxLayout(self)
        root.setContentsMargins(48, 36, 48, 36)
        root.setAlignment(Qt.AlignmentFlag.AlignTop | Qt.AlignmentFlag.AlignHCenter)
        shell = QFrame()
        shell.setObjectName('BalanceShell')
        shell.setFixedWidth(720)
        shell.setStyleSheet('\n            QFrame#BalanceShell {\n                background: #FFFFFF;\n                border-radius: 28px;\n                border: 1px solid #EEF0F3;\n            }\n            ')
        shadow = QGraphicsDropShadowEffect(shell)
        shadow.setBlurRadius(28)
        shadow.setOffset(0, 8)
        shadow.setColor(QColor(16, 24, 40, 28))
        shell.setGraphicsEffect(shadow)
        shell_lay = QVBoxLayout(shell)
        shell_lay.setContentsMargins(22, 22, 22, 22)
        shell_lay.setSpacing(18)
        hero = QFrame()
        hero.setObjectName('BalanceHero')
        hero.setMinimumHeight(168)
        hero.setStyleSheet('\n            QFrame#BalanceHero {\n                background: qlineargradient(\n                    x1:0, y1:0, x2:1, y2:1,\n                    stop:0 #1E4FD6, stop:0.55 #2B6FE8, stop:1 #3B8CF0\n                );\n                border-radius: 22px;\n            }\n            ')
        hero_lay = QVBoxLayout(hero)
        hero_lay.setContentsMargins(28, 24, 28, 24)
        hero_lay.setSpacing(10)
        top_row = QHBoxLayout()
        caption = QLabel('Uliwmalıq balans')
        caption.setStyleSheet('color: rgba(255,255,255,0.92); font-size: 16px; font-weight: 700;')
        top_row.addWidget(caption)
        top_row.addStretch()
        deco = QLabel('◇  ◆')
        deco.setStyleSheet('color: rgba(255,255,255,0.22); font-size: 28px; font-weight: 300;')
        top_row.addWidget(deco)
        hero_lay.addLayout(top_row)
        hero_lay.addStretch(1)
        amount_row = QHBoxLayout()
        amount_row.setSpacing(12)
        self._total = QLabel('0')
        self._total.setStyleSheet('color: #FFFFFF; font-size: 44px; font-weight: 900;')
        self._total.setFont(QFont('Segoe UI', 40, QFont.Weight.Bold))
        amount_row.addWidget(self._total)
        uzs = QLabel('UZS')
        uzs.setStyleSheet('color: rgba(255,255,255,0.95); font-size: 22px; font-weight: 700;')
        amount_row.addWidget(uzs, 0, Qt.AlignmentFlag.AlignBottom)
        amount_row.addStretch()
        hero_lay.addLayout(amount_row)
        shell_lay.addWidget(hero)
        row = QHBoxLayout()
        row.setSpacing(16)
        self._safe_card, self._safe_value = self._mini_card('🔒', '#F43F8A', 'Ceyf balansi')
        self._cash_card, self._cash_value = self._mini_card('$', '#7C5CFC', 'Kutilgan kassa')
        row.addWidget(self._safe_card, 1)
        row.addWidget(self._cash_card, 1)
        shell_lay.addLayout(row)
        root.addWidget(shell)
        root.addStretch(1)
    def _mini_card(self, icon_text: str, icon_bg: str, caption: str) -> tuple[QFrame, QLabel]:
        card = QFrame()
        card.setObjectName('BalanceMini')
        card.setMinimumHeight(150)
        card.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        card.setStyleSheet('\n            QFrame#BalanceMini {\n                background: #FFFFFF;\n                border-radius: 20px;\n                border: 1px solid #F0F1F4;\n            }\n            ')
        sh = QGraphicsDropShadowEffect(card)
        sh.setBlurRadius(18)
        sh.setOffset(0, 4)
        sh.setColor(QColor(16, 24, 40, 22))
        card.setGraphicsEffect(sh)
        lay = QVBoxLayout(card)
        lay.setContentsMargins(22, 20, 22, 18)
        lay.setSpacing(10)
        icon = QLabel(icon_text)
        icon.setFixedSize(44, 44)
        icon.setAlignment(Qt.AlignmentFlag.AlignCenter)
        icon.setStyleSheet(f'background: {icon_bg}; color: #FFFFFF; border-radius: 22px;font-size: 18px; font-weight: 900;')
        lay.addWidget(icon, 0, Qt.AlignmentFlag.AlignLeft)
        value = QLabel('0')
        value.setStyleSheet('color: #101828; font-size: 28px; font-weight: 900;')
        lay.addWidget(value)
        cap = QLabel(caption)
        cap.setStyleSheet('color: #98A2B3; font-size: 14px; font-weight: 600;')
        lay.addWidget(cap)
        lay.addStretch(1)
        return (card, value)
    def set_values(self, total: float, safe: float, cash: float) -> None:
        self._total.setText(_fmt(total))
        self._safe_value.setText(_fmt(safe))
        self._cash_value.setText(_fmt(cash))